<section id="panel-wptools" class="panel">
      <div class="card">
        <div class="th"><div><div class="tt"><i class="fas fa-screwdriver-wrench"></i>Verfügbare Werkzeuge</div><div class="hint">Importieren, exportieren, sichern und die Website prüfen – wie bei WordPress unter „Werkzeuge“.</div></div></div>
        <div class="wpt-grid">
          <div class="wpt-card" id="wptImport"><h3><i class="fas fa-file-import"></i> Daten importieren</h3><p class="hint">Beiträge aus einer JSON-Exportdatei übernehmen (auch von einer anderen Website mit diesem CMS). Höchstens 200 Beiträge pro Import; neu importierte Beiträge werden standardmäßig als Entwurf angelegt.</p><button type="button" class="btn-a" onclick="WpTools.importPosts()"><i class="fas fa-file-arrow-up"></i> JSON-Datei wählen</button></div>
          <div class="wpt-card" id="wptExport"><h3><i class="fas fa-file-export"></i> Daten exportieren</h3><p class="hint">Alle nicht gelöschten Beiträge als JSON-Datei herunterladen – zum Archivieren oder Umziehen.</p><button type="button" class="btn-a" onclick="WpTools.exportPosts()"><i class="fas fa-download"></i> Beiträge exportieren</button></div>
          <div class="wpt-card"><h3><i class="fas fa-clock-rotate-left"></i> Vollständiges Backup</h3><p class="hint">Sicherung aller Inhalte, Einstellungen und (optional) Medien erstellen oder wiederherstellen.</p><button type="button" class="btn-g" onclick="cmsGoto('backups');window.SystemManager?.loadBackup()"><i class="fas fa-arrow-right"></i> Zu den Backups</button></div>
          <div class="wpt-card"><h3><i class="fas fa-heart-pulse"></i> Website-Zustand</h3><p class="hint">Selbstdiagnose von Server, Anmeldung, Daten und Dateisystem mit Verbesserungshinweisen.</p><button type="button" class="btn-g" onclick="WpTools.health()"><i class="fas fa-arrow-right"></i> Zustand prüfen</button></div>
          <div class="wpt-card"><h3><i class="fas fa-user-shield"></i> Datenschutz</h3><p class="hint">Personenbezogene Daten exportieren oder löschen (Kommentare, Einsendungen, Mitglieder).</p><button type="button" class="btn-g" onclick="cmsGoto('privacy');window.ToolsManager?.loadPrivacy()"><i class="fas fa-arrow-right"></i> Zum Datenschutz</button></div>
          <div class="wpt-card"><h3><i class="fas fa-person-digging"></i> Wartungsmodus &amp; Weiterleitungen</h3><p class="hint">Website vorübergehend sperren, 301/302-Weiterleitungen und Fehlerseiten verwalten.</p><button type="button" class="btn-g" onclick="cmsGoto('maintenance');window.ToolsManager?.loadMaint()"><i class="fas fa-arrow-right"></i> Wartungsmodus</button> <button type="button" class="btn-g" onclick="cmsGoto('redirects');window.ToolsManager?.loadRules()"><i class="fas fa-arrow-right"></i> Weiterleitungen</button></div>
        </div>
      </div>
    </section>
