<?php
// Prüft Block-Themes (Full Site Editing): theme.json → Global Styles, Vorlagen/Vorlagenteile/Muster, Query-Loop, Navigation, Suche, Layout. Aufruf: php scripts/test-wp-fse.php
declare(strict_types=1);
$tmp=sys_get_temp_dir().'/elvado-fse-'.bin2hex(random_bytes(4));mkdir($tmp);mkdir($tmp.'/wp-content');mkdir($tmp.'/cms');
$th=$tmp.'/wp-content/themes/blocky';foreach(['','/templates','/parts','/patterns'] as $d)mkdir($th.$d,0775,true);
define('WP_CONTENT_DIR',$tmp.'/wp-content');define('ELVADO_WP_DATA',$tmp.'/cms/.wp');define('ELVADO_WP_CMS_DATA',$tmp.'/cms');$_SERVER['HTTP_HOST']='example.test';$_SERVER['REMOTE_ADDR']='203.0.113.5';
$news=[];for($i=1;$i<=4;$i++)$news[]=['id'=>$i,'slug'=>"beitrag-$i",'title'=>"Beitrag $i",'category'=>'News','tags'=>'','excerpt'=>"Auszug $i",'body_html'=>"<p>Inhalt $i</p>",'date'=>"2026-0$i-10",'published'=>true,'status'=>'published'];
file_put_contents($tmp.'/cms/news.json',json_encode($news));
file_put_contents($tmp.'/cms/site.json',json_encode(['portal'=>['site_name'=>'Blockradio','tagline'=>'Hör rein'],'menus'=>['top'=>[['id'=>'m1','label'=>'Start','target'=>'system:start','enabled'=>true,'parent_id'=>'']],'bottom'=>[]],'pages'=>[]]));
file_put_contents($th.'/style.css',"/*\nTheme Name: Blocky\nVersion: 1.0\n*/\n");
file_put_contents($th.'/theme.json',json_encode(['version'=>3,'settings'=>['layout'=>['contentSize'=>'640px','wideSize'=>'1000px'],'useRootPaddingAwareAlignments'=>true,'color'=>['palette'=>[['slug'=>'accent','color'=>'#ff3366','name'=>'Akzent']],'defaultPalette'=>false],'typography'=>['fontSizes'=>[['slug'=>'big','size'=>'2rem','name'=>'Groß']]],'custom'=>['lineHeight'=>['body'=>1.6]]],
 'styles'=>['color'=>['background'=>'#fafafa','text'=>'#111'],'spacing'=>['padding'=>['left'=>'20px','right'=>'20px','top'=>'0','bottom'=>'0'],'blockGap'=>'1rem'],'elements'=>['link'=>['color'=>['text'=>'var:preset|color|accent']]],'blocks'=>['core/post-title'=>['typography'=>['fontSize'=>'var:preset|font-size|big']]]]]));
file_put_contents($th.'/parts/header.html','<!-- wp:group {"layout":{"type":"flex","justifyContent":"space-between"}} --><div class="wp-block-group"><!-- wp:site-title /--><!-- wp:navigation /--></div><!-- /wp:group -->');
file_put_contents($th.'/parts/footer.html','<!-- wp:paragraph --><p>Fußzeile TEST</p><!-- /wp:paragraph -->');
file_put_contents($th.'/patterns/loop.php',"<?php\n/**\n * Title: Loop\n * Slug: blocky/loop\n */\n?>\n<!-- wp:query {\"query\":{\"perPage\":2,\"postType\":\"post\",\"inherit\":true}} -->\n<div class=\"wp-block-query\"><!-- wp:post-template --><!-- wp:post-title {\"isLink\":true} /--><!-- wp:post-date /--><!-- /wp:post-template --><!-- wp:query-pagination --><!-- wp:query-pagination-next /--><!-- /wp:query-pagination --></div>\n<!-- /wp:query -->");
file_put_contents($th.'/templates/index.html','<!-- wp:template-part {"slug":"header"} /--><!-- wp:group {"tagName":"main","layout":{"type":"constrained"}} --><main class="wp-block-group"><!-- wp:pattern {"slug":"blocky/loop"} /--></main><!-- /wp:group --><!-- wp:template-part {"slug":"footer"} /-->');
file_put_contents($th.'/templates/single.html','<!-- wp:template-part {"slug":"header"} /--><!-- wp:post-title {"level":1} /--><!-- wp:post-content {"layout":{"type":"constrained"}} /--><!-- wp:search {"label":"Suche","buttonText":"Los"} /--><!-- wp:template-part {"slug":"footer"} /-->');
require __DIR__.'/_testdb.php';
require __DIR__.'/../cms/wp/load.php';require __DIR__.'/../cms/wp/router.php';require __DIR__.'/../cms/wp/rest.php';require __DIR__.'/../cms/wp/site-editor.php';
$fail=0;$n=0;
function t(string $name,bool $ok,string $extra=''): void { global $fail,$n; $n++; if(!$ok){$fail++;echo "FEHLER: $name $extra\n";} }
$GLOBALS['ELVADO_SITE']=json_decode((string)file_get_contents($tmp.'/cms/site.json'),true);
update_option('stylesheet','blocky');update_option('template','blocky');
elvado_wp_boot(['theme'=>true]);
t('Block-Theme erkannt',wp_is_block_theme());
$css=wp_get_global_stylesheet();
t('Preset-Variable Farbe',str_contains($css,'--wp--preset--color--accent:#ff3366'));
t('Preset-Klasse',str_contains($css,'.has-accent-color'));
t('Schriftgröße',str_contains($css,'--wp--preset--font-size--big:2rem'));
t('Eigener Wert',str_contains($css,'--wp--custom--line-height--body:1.6'));
t('Inhaltsbreite',str_contains($css,'--wp--style--global--content-size:640px'));
t('Link-Farbe aus Preset',str_contains($css,'var(--wp--preset--color--accent)'));
t('Block-Stil Beitragstitel',str_contains($css,'wp-block-post-title'));
t('Kern-Palette abgeschaltet',!str_contains($css,'--wp--preset--color--vivid-red'));
$r=elvado_wp_dispatch('/');$b=$r['body'];
t('Startseite 200',$r['status']===200,(string)$r['status']);
t('Header-Teil mit Titel',str_contains($b,'wp-block-site-title')&&str_contains($b,'Blockradio'));
t('Navigation aus CMS-Menü',str_contains($b,'wp-block-navigation-item__label">Start'));
t('Muster + Query-Loop',str_contains($b,'Beitrag 4')&&str_contains($b,'wp-block-post-template'));
t('Footer-Teil',str_contains($b,'Fußzeile TEST'));
t('Layout-Klassen',str_contains($b,'is-layout-constrained')&&str_contains($b,'is-layout-flex'));
t('Global Styles im Head',str_contains($b,'id="global-styles-inline-css"'));
t('Block-Library-CSS',str_contains($b,'/wp-includes/css/dist/block-library/style.min.css'));
$css2=elvado_wp_dispatch('/wp-includes/css/dist/block-library/style.min.css');
t('Block-Library-CSS wird ausgeliefert',$css2['status']===200&&strlen($css2['body'])>50000);
$p=elvado_wp_dispatch('/beitrag-1/');$pb=$p['body'];
t('Beitrag 200',$p['status']===200);
t('Beitragstitel h1',(bool)preg_match('#<h1[^>]*wp-block-post-title[^>]*>Beitrag 1#',$pb));
t('Beitragsinhalt',str_contains($pb,'Inhalt 1'));
t('Suchformular',str_contains($pb,'wp-block-search__input')&&str_contains($pb,'>Los<'));
t('Kein Rohmarkup',!str_contains($b.$pb,'<!-- wp:'));
// Website-Editor: eigene Fassungen, Muster-Auflösung, Palette, REST für Vorlagenteile
$orig=elvado_wp_se_content('template','index');
t('Editor: Muster werden ersetzt',$orig!==null&&!str_contains($orig,'wp:pattern')&&str_contains($orig,'wp:query'));
t('Editor: Liste mit Vorlagen und Teilen',count(elvado_wp_se_list()['template'])>=2&&count(elvado_wp_se_list()['part'])===2);
t('Editor: speichern',elvado_wp_se_save('template','index','<!-- wp:paragraph --><p>UEBERSCHRIEBEN</p><!-- /wp:paragraph -->'));
t('Editor: Website nutzt die eigene Fassung',str_contains(elvado_wp_dispatch('/')['body'],'UEBERSCHRIEBEN'));
t('Editor: Liste markiert eigene Fassung',(function(){ foreach(elvado_wp_se_list()['template'] as $x)if($x['slug']==='index')return $x['custom']; return false; })());
t('Editor: zurücksetzen',elvado_wp_se_reset('template','index')&&!str_contains(elvado_wp_dispatch('/')['body'],'UEBERSCHRIEBEN'));
t('Editor: ungültiger Name abgelehnt',!elvado_wp_se_save('template','../x','a')||!is_file(elvado_wp_se_dir('templates').'/../x.html'));
elvado_wp_se_save_palette(['accent'=>'#00ff00']);
t('Editor: Palette wirkt in Global Styles',str_contains(wp_get_global_stylesheet(),'--wp--preset--color--accent:#00ff00'));
t('Editor: Farbe ungültig → Standard',(function(){ elvado_wp_se_save_palette(['accent'=>'rot;x']);$c=wp_get_global_stylesheet();return str_contains($c,'--wp--preset--color--accent:#ff3366')||(print_r(array_map(fn($x)=>$x['color'],elvado_wp_se_palette()),true)&&false); })());
$GLOBALS['elvado_wp_user']=['id'=>1,'login'=>'admin','role'=>'administrator','caps'=>elvado_wp_caps_for_role('administrator')];
$tp=elvado_wp_rest_dispatch('GET','/wp/v2/template-parts/blocky//header');
t('REST: Vorlagenteil als Datensatz',$tp['status']===200&&str_contains($tp['body'],'wp-block-group')||str_contains($tp['body'],'wp:group'),$tp['body']);
$op=elvado_wp_rest_dispatch('OPTIONS','/wp/v2/settings');
t('REST: OPTIONS liefert Allow',$op['status']===200&&isset($op['headers']['Allow']),json_encode($op['headers']));
$sr=elvado_wp_rest_dispatch('GET','/wp/v2/block-renderer/core/site-title');
t('REST: Block-Renderer',$sr['status']===200&&str_contains($sr['body'],'Blockradio'),$sr['body']);
$log=@file_get_contents(ELVADO_WP_DATA.'/debug.log');t('Keine Fehler im Protokoll',!$log||!preg_match('/Error|Exception/',$log),substr((string)$log,-300));
system('rm -rf '.escapeshellarg($tmp));
echo $fail?"$fail von $n fehlgeschlagen\n":"$n von $n Prüfungen bestanden\n";exit($fail?1:0);
